# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.player_model.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'player_model', 'function_path': 'animated_java:player_model/animations/pause_all'}
tag @s remove aj.player_model.animation.breathe.playing
tag @s remove aj.player_model.animation.look.playing
tag @s remove aj.player_model.animation.bored.playing
tag @s remove aj.player_model.animation.talk.playing
tag @s remove aj.player_model.animation.walk.playing