# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.player_model.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:player_model/as_root/pre_tick
execute if entity @s[tag=aj.player_model.animation.breathe.playing] run function animated_java:player_model/animations/breathe/zzz/on_tick
execute if entity @s[tag=aj.player_model.animation.look.playing] run function animated_java:player_model/animations/look/zzz/on_tick
execute if entity @s[tag=aj.player_model.animation.bored.playing] run function animated_java:player_model/animations/bored/zzz/on_tick
execute if entity @s[tag=aj.player_model.animation.talk.playing] run function animated_java:player_model/animations/talk/zzz/on_tick
execute if entity @s[tag=aj.player_model.animation.walk.playing] run function animated_java:player_model/animations/walk/zzz/on_tick
execute on passengers if entity @s[tag=aj.player_model.data] run function animated_java:player_model/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:player_model/as_root/post_tick