# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.player_model.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'player_model', 'function_path': 'animated_java:player_model/variants/default/apply'}
execute on passengers if entity @s[tag=aj.player_model.bone.h_head] run function animated_java:player_model/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.player_model.bone.right_arm] run function animated_java:player_model/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.player_model.bone.left_arm] run function animated_java:player_model/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.player_model.bone.torso] run function animated_java:player_model/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.player_model.bone.right_leg] run function animated_java:player_model/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.player_model.bone.left_leg] run function animated_java:player_model/variants/default/zzz/5