# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.breathe.frame dummy
scoreboard objectives add aj.look.frame dummy
scoreboard objectives add aj.bored.frame dummy
scoreboard objectives add aj.talk.frame dummy
scoreboard objectives add aj.walk.frame dummy
execute as @e[type=item_display,tag=aj.player_model.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:player_model/root/on_load