# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:player_model/animations/player_model.breathe/zzz/apply_frame {frame: 50}
scoreboard players add @s aj.player_model.breathe.frame 1