# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.player_model.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'player_model', 'function_path': 'animated_java:player_model/animations/look/play'}
tag @s add aj.player_model.animation.look.playing
scoreboard players set @s aj.look.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:player_model/animations/look/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only